name: Django App Deployment

on:
  push:
    branches:
      - main

jobs:
  build:
    steps:
      - name: Update ubuntu repos with curl installation
        run: sudo apt update -y && sudo apt install -y curl

      - name: Install python3 and pip3
        run: sudo apt install -y python3-full

      - name: Install NodeJS
        run: cd ~ && curl -sL https://deb.nodesource.com/setup_18.x -o /tmp/nodesource_setup.sh && sudo bash /tmp/nodesource_setup.sh && sudo apt install -y nodejs

      - name: Install pm2
        run: sudo npm install pm2@latest -g

      - name: create virtual environment
        run: python3 -m venv venv

      - name: Install depenendencies in virtual env
        run: ~/code/venv/bin/pip3 install -r requirements.txt

      - name: Run migrations
        run: ~/code/venv/bin/python3 manage.py migrate

  deploy:
    steps:
      - name: Start App with pm2
        run: pm2 start "~/code/venv/bin/python3 manage.py runserver 0.0.0.0:8000"

      - name: Save pm2 config
        run: pm2 save
